CREATE TABLE `wcg` (
	`pchar` CHAR DEFAULT NULL,
	`pint` INT DEFAULT NULL,
	`pint` INT DEFAULT NULL,
	`pliste` VARCHAR DEFAULT NULL,
	`poiu` VARCHAR DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `wcg` (`pchar`, `pint`, `pint`, `pliste`, `poiu`) VALUES
('N', 1, 'Denton', 'barracks'),
('J', 8, 'Salinas', 'tickles'),
('L', 4, 'Charlotte', 'gallivants'),
('N', 67, 'Monterey', 'undulates'),
('F', 4, 'Daly City', 'class'),
('U', 67, 'Jackson', 'formulizes'),
('F', 5, 'Muskegon', 'drop-forge'),
('U', 5, 'Boise City', 'wattles'),
('E', 4, 'Charlotte', 'fulgurate'),
('X', 5, 'Salinas', 'alleviated'),
('W', 1, 'Lincoln', 'habituate'),
('T', 14, 'West Valley City', 'laud'),
('P', 4, 'Santa Maria', 'decarburize'),
('E', 4, 'Bridgeport', 'pity'),
('P', 8, 'Santa Rosa', 'outstrips'),
('H', 67, 'Santa Barbara', 'concatenate'),
('S', 8, 'Springdale', 'calm'),
('S', 5, 'Victorville', 'barrack'),
('V', 67, 'Oklahoma City', 'breezed'),
('Q', 5, 'Mesa', 'accords'),
('B', 8, 'Hemet', 'scathed'),
('L', 8, 'Anchorage', 'legalised'),
('W', 67, 'Sterling Heights', 'memorialising'),
('I', 8, 'Tyler', 'prills'),
('D', 14, 'Cincinnati', 'replay'),
('D', 1, 'Lancaster', 'jilts'),
('H', 5, 'Mobile', 'hastens'),
('L', 67, 'Des Moines', 'deprecating'),
('Q', 5, 'Boise City', 'indicts'),
('O', 1, 'Moreno Valley', 'knifes'),
('F', 8, 'Atlanta', 'parade'),
('O', 14, 'Youngstown', 'behaved'),
('L', 14, 'Ocala', 'variolates'),
('X', 14, 'Raleigh', 'sacks'),
('V', 67, 'Pembroke Pines', 'arrive'),
('Z', 5, 'Scottsdale', 'bewilders'),
('M', 67, 'Vallejo', 'overcalls'),
('P', 4, 'Deltona', 'peroxide'),
('T', 4, 'Fullerton', 'complexify'),
('M', 8, 'Myrtle Beach', 'sprigging'),
('Z', 5, 'Henderson', 'outmove'),
('P', 67, 'Burbank', 'flyblow'),
('T', 8, 'Warren', 'misapply'),
('N', 8, 'Knoxville', 'giggled'),
('B', 14, 'Saginaw', 'migrated'),
('U', 1, 'Indianapolis', 'follow-throughs'),
('Q', 8, 'Waco', 'rents'),
('J', 1, 'Nashua', 'outlaunch'),
('J', 1, 'Minneapolis', 'smiled'),
('P', 67, 'Lexington', 'hunch'),
('Z', 67, 'Tempe', 'hobbling'),
('Z', 1, 'Fairfield', 'garrottings'),
('E', 8, 'Asheville', 'rewrites'),
('A', 5, 'Ontario', 'vitaminizes'),
('B', 5, 'Cambridge', 'fragging'),
('X', 1, 'Trenton', 'unionise'),
('J', 67, 'South Bend', 'outstared'),
('J', 1, 'Clarke County', 'wean'),
('G', 5, 'Punta Gorda', 'needs'),
('F', 67, 'Lowell', 'sparkled'),
('O', 1, 'Shreveport', 'horde'),
('F', 8, 'Carrollton', 'wimbled'),
('Z', 4, 'Bel Air', 'draughts'),
('W', 1, 'St. Louis', 'institutes'),
('G', 5, 'Port Orange', 'compose'),
('N', 14, 'San Diego', 'outdrove'),
('Q', 67, 'Miami', 'neutralizes');